# Generated by Django 6.1 on 2026-08-15 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='series/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='speakers/')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('scripture_reference', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='sermons/audio/')),
                ('notes_pdf', models.FileField(blank=True, upload_to='sermons/notes/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='sermons/thumbnails/')),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.series')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.speaker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
