# Generated by Django 6.1 on 2026-09-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('visit_date', models.DateTimeField(help_text='Which Sunday are you planning to visit?')),
                ('group_size', models.PositiveIntegerField(default=1, help_text='How many people are coming?')),
                ('has_children', models.BooleanField(default=False, help_text='Is there any children?')),
                ('how_heard', models.CharField(choices=[('friend', 'Friend or Family'), ('social', 'Social Media'), ('flyer', 'Flyer or Poster'), ('walked', 'Walked Past the Church'), ('other', 'Other')], default='friend', max_length=10)),
                ('questions', models.TextField(blank=True, help_text='Any questions  before you visit?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Has the team followed up?')),
            ],
            options={
                'verbose_name': 'Planned Visit',
                'verbose_name_plural': 'Planned Visits',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
