# Generated by Django 6.1 on 2026-08-15 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('youth', 'Youth Ministry'), ('men', "Men's Ministry"), ('women', "Women's Ministry"), ('children', "Children's Ministry"), ('outreach', 'Outreach & Missions')], max_length=10)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='ministries/')),
                ('leader', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('group_type', models.CharField(choices=[('mixed', 'Mixed'), ('men', "Men's"), ('women', "Women's"), ('youth', 'Youth'), ('couples', 'Couples'), ('seniors', 'Seniors')], default='mixed', max_length=10)),
                ('description', models.TextField()),
                ('meeting_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('meeting_time', models.TimeField()),
                ('location_area', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(blank=True, null=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='ministries.ministry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='ministries.smallgroup')),
            ],
        ),
    ]
