# Generated by Django 6.1 on 2026-08-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='name',
        ),
    ]
