# Generated by Django 6.1 on 2026-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_remove_ministry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='type',
            field=models.CharField(choices=[('youth', 'Youth Ministry'), ('men', "Men's Ministry"), ('women', "Women's Ministry"), ('children', "Children's Ministry"), ('outreach', 'Outreach & Missions')], max_length=30, unique=True),
        ),
    ]
